plugins {
    id 'com.android.application'
}

android {
    compileSdk 37
    buildFeatures {
        viewBinding = true
        resValues = true
    }
    defaultConfig {
        minSdk 30
        targetSdk 37
        versionCode 17
        versionName "3.0.0"
        applicationId "mf.asciitext.lite"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resValue "string", "versionName", versionName
        resValue "string", "rateUri", "https://play.google.com/store/apps/details?id=" + applicationId
    }
    buildTypes {
        debug {
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'mf.irregex'
    lint {
        abortOnError true
        checkReleaseBuilds true
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
}
